# Generated by Django 5.0.3 on 2024-03-30 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=75, unique=True)),
                ('province', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('manager', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('street', models.CharField(max_length=25)),
                ('province', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('secretkey', models.CharField(blank=True, default=None, max_length=7, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('image', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=150)),
                ('music_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jpartyapp.musicgenre')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jpartyapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserAssist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jpartyapp.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jpartyapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jpartyapp.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jpartyapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jpartyapp.musicgenre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jpartyapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=45, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jpartyapp.user')),
            ],
        ),
    ]
